title: DarwinKVM Docs
description: An Advanced Template for running macOS within QEMU/KVM. Run the latest macOS on QEMU/KVM with libvirtd/Virt-Manager, includes Single GPU Passthrough.
theme: just-the-docs

url: https://royalgraphx.github.io/DarwinKVM/docs

aux_links:
  Template Repository: https://github.com/royalgraphx/DarwinKVM/docs
